In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2440, 5135, 7102, 3362],
 [2440, 5135, 7102, 9880],
 [2440, 7145, 7102, 110],
 [4856, 1407, 6848, 4905, 4804],
 [4856, 1407, 6848, 4905, 5550],
 [2895, 2440, 6977, 7102, 2155],
 [1192, 7246, 7901, 4905]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2440 5135 7102 3362]
 [   0    0    0    0 2440 5135 7102 9880]
 [   0    0    0    0 2440 7145 7102  110]
 [   0    0    0 4856 1407 6848 4905 4804]
 [   0    0    0 4856 1407 6848 4905 5550]
 [   0    0    0 2895 2440 6977 7102 2155]
 [   0    0    0    0 1192 7246 7901 4905]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 345ms/step


array([[[ 0.01625099,  0.0454924 ,  0.03891038,  0.03318248,
          0.0211242 , -0.03774709, -0.00884492,  0.02047025,
          0.00531366, -0.02340179],
        [ 0.01625099,  0.0454924 ,  0.03891038,  0.03318248,
          0.0211242 , -0.03774709, -0.00884492,  0.02047025,
          0.00531366, -0.02340179],
        [ 0.01625099,  0.0454924 ,  0.03891038,  0.03318248,
          0.0211242 , -0.03774709, -0.00884492,  0.02047025,
          0.00531366, -0.02340179],
        [ 0.01625099,  0.0454924 ,  0.03891038,  0.03318248,
          0.0211242 , -0.03774709, -0.00884492,  0.02047025,
          0.00531366, -0.02340179],
        [ 0.04839804,  0.02482799,  0.041677  , -0.0083468 ,
          0.02847901,  0.03783533,  0.02149886, -0.02700822,
         -0.04516671,  0.04392742],
        [ 0.00754644,  0.00359685, -0.02905368,  0.03366523,
         -0.02352716, -0.04488162, -0.02087953, -0.01359068,
         -0.01210867,  0.01062919],
        [ 0.0235143 ,  0.03173623, -0.0451542 ,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2440, 5135, 7102, 3362])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 85ms/step


array([[ 0.01625099,  0.0454924 ,  0.03891038,  0.03318248,  0.0211242 ,
        -0.03774709, -0.00884492,  0.02047025,  0.00531366, -0.02340179],
       [ 0.01625099,  0.0454924 ,  0.03891038,  0.03318248,  0.0211242 ,
        -0.03774709, -0.00884492,  0.02047025,  0.00531366, -0.02340179],
       [ 0.01625099,  0.0454924 ,  0.03891038,  0.03318248,  0.0211242 ,
        -0.03774709, -0.00884492,  0.02047025,  0.00531366, -0.02340179],
       [ 0.01625099,  0.0454924 ,  0.03891038,  0.03318248,  0.0211242 ,
        -0.03774709, -0.00884492,  0.02047025,  0.00531366, -0.02340179],
       [ 0.04839804,  0.02482799,  0.041677  , -0.0083468 ,  0.02847901,
         0.03783533,  0.02149886, -0.02700822, -0.04516671,  0.04392742],
       [ 0.00754644,  0.00359685, -0.02905368,  0.03366523, -0.02352716,
        -0.04488162, -0.02087953, -0.01359068, -0.01210867,  0.01062919],
       [ 0.0235143 ,  0.03173623, -0.0451542 ,  0.01604866, -0.02121249,
         0.04630741, -0.00634579, -0.03447889